module.exports = {
    context: {
        sub: '',
        contextType: 'project, request, task',
        name: '',
        value: {},
    },
    project: {
        sub: '',
        name: 'Animal Photos',
        context: {},
    },
    requestTemplate: {
        method: 'GET',
        protocol: 'HTTPS',
        url: 'https://api:${request.project.port}/${request.sub.defaultQuery}',
        query: {},
        path: {},
        header: {},
        body: {},
        context: {},
    },
    request: {
        project:'',
        name: '',
        description: 'This request returns a cat photo',
        requestTemplate: '',
        requestPermission: 'any, project, none',
        requestAvailableAs: 'taskRequest',
        resultPermission: 'any, project, none',
        resultAvailableAs:'taskResponse',
        requestType: 'request, transform',
        transformType: 'request, response, task',
        successCodes: ['200', '300-399'],
        errorCodes: ['400-500'],
        requestTransformers: [],
        responseTransformers: [],
        ifRequestTransformFails: 'continue, stop workflow, repeat attempt',
        ifResponseTransformFails: 'continue, stop workflow, repeat attempt',
    },
    task: {
        sub: '',
        request:'',
        ifTaskFails: 'stop workflow, continue, repeat attempt',
        repeatTaskPerResultPath: 'getCatPhotoResponse, getDogPhotoResponse',
        context: {},
    },
    workflow: {
        name: '',
        sub: '',
        tasks: [task],
        timeout: '',
        onTimeout: 'timeout, send 200 and continue, send 500 and continue',
    },
    instance: {
        sub: '',
        workflow: '',
    },
    stat: {
        sub: '',
        instance: '',
        requestName: '',
        payloadType: 'request, response',
        size: '',
        statusCode: '',
        statusMessage: '',
        payload: {},
    }
}